apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Release.Name }}-amf-nad
  namespace: open5gs
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": {{- cat .Values.config.multusIpvlanMasterInt | nospace | quote }},
      "mode": "l2",
      "ipam": {
          "type": "static",
          "addresses": [
                  {
                    "address": {{- cat .Values.config.amfMultusIP "/" .Values.config.multusNetworkMask | nospace | quote }}
                  }
          ]
        }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Release.Name }}-smf-nad
  namespace: open5gs
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": {{- cat .Values.config.multusIpvlanMasterInt | nospace | quote }},
      "mode": "l2",
      "ipam": {
          "type": "static",
          "addresses": [
                  {
                    "address": {{- cat .Values.config.smfMultusIP "/" .Values.config.multusNetworkMask | nospace | quote }}
                  }
          ]
        }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Release.Name }}-upf-nad
  namespace: open5gs
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": {{- cat .Values.config.multusIpvlanMasterInt | nospace | quote }},
      "mode": "l2",
      "ipam": {
          "type": "static",
          "addresses": [
                  {
                    "address": {{- cat .Values.config.upfMultusIP "/" .Values.config.multusNetworkMask | nospace | quote }}
                  }
          ]
        }
    }'     