# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: registry.gitlab.com/infinitydon/registry/open5gs-aio
    pullPolicy: IfNotPresent
    tag: "v2.4.9-prom"

ueransim:
   repository: registry.gitlab.com/infinitydon/registry/ueransim
   pullPolicy: IfNotPresent
   tag: "v3.2.6"   
   ue:
     imsi: imsi-208930000000031
     imei: "356938035643803"
     imeiSv: "4370816125816151"
     op: "63bfa50ee6523365ff14c1f45f88737d"
     secKey: "0C0A34601D4F07677303652C0462535B"    

k8swait:
   repository: groundnuty/k8s-wait-for
   pullPolicy: IfNotPresent
   tag: "v1.4"

webui:
  image:
    repository: registry.gitlab.com/infinitydon/registry/open5gs-webui
    pullPolicy: IfNotPresent
    tag: "v2.4.5"
  ingress:
    enabled: false
    ## Ingress annotations done as key:value pairs
    ## For a full list of possible ingress annotations, please see
    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
    ##
    ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
    # annotations:
    #   kubernetes.io/ingress.class: nginx

    hosts:
      - name: open5gs-epc.local
        paths: ["/"]
        ## Set this to true in order to enable TLS on the ingress record
        tls: false

        ## Optionally specify the TLS hosts for the ingress record
        ## Useful when the Ingress controller supports www-redirection
        ## If not specified, the above host name will be used
        # tlsHosts:
        # - www.open5gs-epc.local
        # - open5gs-epc.local

        ## If TLS is set to true, you can declare what secret will store the key/certificate for TLS
        # tlsSecret: open5gs-epc.local-tls    

dnn: internet  

config:
  multusPodInterfaceName: "net1"
  multusIpvlanMasterInt: "enp0s9"
  upfMultusIP: "192.168.70.2"    
  amfMultusIP: "192.168.70.3"
  smfMultusIP: "192.168.70.4"
  multusNetworkMask: "24"
  amfPort: "38412"
  mcc: 208
  mnc: 93
  tac: 7
  sd: 1
  sst: 1

# Primary/Native kubernetes interface
k8s:
 interface: eth0